# map_data.py

# Tọa độ của các tỉnh
PROVINCES = {
    "Thanh Hóa": (8.2, 2.2),
    "Ninh Bình": (9.3, 3),
    "Nam Định": (10.1, 3.4),
    "Thái Bình": (10.4, 4),
    "Hà Nam": (9.3, 4.2),
    "Hòa Bình": (8, 4.3),
    "Hà Tây": (8.6, 5),
    "Hưng Yên": (9.5, 4.7),
    "Hải Dương": (10.3, 5.1),
    "Hải Phòng": (11, 4.5),
    "Quảng Ninh": (12.5, 5.8),
    "Bắc Giang": (10.4, 6.2),
    "Bắc Ninh": (9.7, 5.6),
    "Hà Nội": (9.1, 6.1),
    "Vĩnh Phúc": (8.5, 6.5),
    "Phú Thọ": (7.4, 6.2),
    "Sơn La": (5, 6.2),
    "Yên Bái": (6.2, 7.5),
    "Tuyên Quang": (7.6, 8.5),
    "Bắc Kạn": (9.2, 8.8),
    "Thái Nguyên": (9.1, 7.2),
    "Lạng Sơn": (10.6, 7.8),
    "Cao Bằng": (9.9, 10),
    "Hà Giang": (7, 10.2),
    "Lào Cai": (5, 9),
    "Lai Châu": (2.5, 8.5),
}

# Khoảng cách giữa các tỉnh liền kề
DISTANCES = {
    ("Thanh Hóa", "Ninh Bình"): 1.49,
    ("Thanh Hóa", "Hòa Bình"): 2.11,
    ("Thanh Hóa", "Sơn La"): 5.12,
    ("Ninh Bình", "Nam Định"): 0.82,
    ("Ninh Bình", "Hà Nam"): 1.00,
    ("Ninh Bình", "Hòa Bình"): 1.70,
    ("Hòa Bình", "Hà Tây"): 0.92,
    ("Hòa Bình", "Hà Nam"): 1.30,
    ("Hòa Bình", "Phú Thọ"): 1.99,
    ("Hòa Bình", "Sơn La"): 3.55,
    ("Sơn La", "Yên Bái"): 1.77,
    ("Sơn La", "Phú Thọ"): 2.40,
    ("Sơn La", "Lào Cai"): 2.80,
    ("Sơn La", "Lai Châu"): 3.40,
    ("Hà Nam", "Hưng Yên"): 0.54,
    ("Hà Nam", "Thái Bình"): 1.12,
    ("Hà Nam", "Nam Định"): 1.13,
    ("Nam Định", "Thái Bình"): 0.67,
    ("Thái Bình", "Hải Phòng"): 0.78,
    ("Thái Bình", "Hải Dương"): 1.10,
    ("Hải Dương", "Bắc Ninh"): 0.78,
    ("Hải Dương", "Hưng Yên"): 0.89,
    ("Hải Dương", "Quảng Ninh"): 2.31,
    ("Hải Phòng", "Quảng Ninh"): 1.98,
    ("Hưng Yên", "Bắc Ninh"): 0.92,
    ("Hưng Yên", "Hà Tây"): 0.95,
    ("Hưng Yên", "Hà Nội"): 1.46,
    ("Hà Tây", "Hà Nội"): 1.21,
    ("Hà Tây", "Vĩnh Phúc"): 1.50,
    ("Hà Tây", "Phú Thọ"): 1.70,
    ("Phú Thọ", "Vĩnh Phúc"): 1.14,
    ("Phú Thọ", "Yên Bái"): 1.77,
    ("Phú Thọ", "Tuyên Quang"): 2.31,
    ("Hà Nội", "Vĩnh Phúc"): 0.72,
    ("Hà Nội", "Bắc Ninh"): 0.78,
    ("Hà Nội", "Thái Nguyên"): 1.10,
    ("Vĩnh Phúc", "Thái Nguyên"): 0.92,
    ("Vĩnh Phúc", "Tuyên Quang"): 2.19,
    ("Bắc Ninh", "Bắc Giang"): 0.92,
    ("Quảng Ninh", "Bắc Giang"): 2.14,
    ("Quảng Ninh", "Lạng Sơn"): 2.76,
    ("Bắc Giang", "Lạng Sơn"): 1.61,
    ("Bắc Giang", "Thái Nguyên"): 1.64,
    ("Lạng Sơn", "Thái Nguyên"): 1.62,
    ("Lạng Sơn", "Bắc Kạn"): 1.72,
    ("Lạng Sơn", "Cao Bằng"): 2.31,
    ("Thái Nguyên", "Bắc Kạn"): 1.60,
    ("Thái Nguyên", "Tuyên Quang"): 1.98,
    ("Tuyên Quang", "Bắc Kạn"): 1.63,
    ("Tuyên Quang", "Hà Giang"): 1.80,
    ("Tuyên Quang", "Yên Bái"): 1.72,
    ("Bắc Kạn", "Cao Bằng"): 1.39,
    ("Yên Bái", "Lào Cai"): 1.92,
    ("Lào Cai", "Lai Châu"): 2.55,
    ("Hà Giang", "Cao Bằng"): 2.91,
    ("Hà Giang", "Yên Bái"): 3.1,
    ("Hà Giang", "Lào Cai"): 2.4,
    ("Hải Dương", "Hải Phòng"): 1,
    ("Hà Tây", "Hà Nam"): 1.2,
    ("Bắc Giang", "Hải Dương"): 1.2,
    ("Bắc Giang", "Hà Nội"): 1.4,
}
